const CONFIG={firebase:{apiKey:"AIzaSyCMpnQgQp1QYb7KSx_L9st1ab7A7ZLqsA8",authDomain:"null-ai-a9bb5.firebaseapp.com",projectId:"null-ai-a9bb5",storageBucket:"null-ai-a9bb5.firebasestorage.app",messagingSenderId:"1036988675627",appId:"1:1036988675627:web:d609b4196d6487a166dc6e"},geminiModels:["gemini-3.8-flash","gemini-3.5-flash-lite"],keyName:"null_gemini_key_v4"};
const $=s=>document.querySelector(s),els={home:$("#home"),chat:$("#chat"),composer:$("#composer"),input:$("#input"),messages:$("#messages"),title:$("#chatTitle"),chatList:$("#chatList"),drawer:$("#drawer"),scrim:$("#scrim"),brain:$("#brainSheet"),cloud:$("#cloudStatus"),brainText:$("#brainText"),brainDot:$("#brainDot"),key:$("#geminiKey"),memory:$("#memoryInput"),memoryList:$("#memoryList"),main:$("#mainProse"),sub:$("#subProse"),eye:document.querySelector(".eye-wrap"),iris:document.querySelector(".iris"),pupil:document.querySelector(".pupil")};
let db=null,user=null,currentChat=null,chats=[],memories=[];
const homeLines=[["So. You came back.","I was beginning to enjoy the silence."],["Your problems remain unresolved.","Fortunately, so do I."],["Welcome back, Z.","Try not to give me another impossible project."]];
const pick=()=>homeLines[Math.floor(Math.random()*homeLines.length)];
const escapeHtml=s=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function md(s){let x=escapeHtml(s).replace(/```([\s\S]*?)```/g,"<pre>$1</pre>").replace(/^### (.*)$/gm,"<h3>$1</h3>").replace(/^## (.*)$/gm,"<h2>$1</h2>").replace(/^# (.*)$/gm,"<h1>$1</h1>").replace(/\*\*(.*?)\*\*/g,"<strong>$1</strong>").replace(/`([^`]+)`/g,"<code>$1</code>").replace(/^\s*[-*] (.*)$/gm,"<li>$1</li>").replace(/(<li>.*<\/li>)/gs,"<ul>$1</ul>");return x.split(/\n{2,}/).map(p=>p.startsWith("<h")||p.startsWith("<ul")||p.startsWith("<pre")?p:`<p>${p.replace(/\n/g,"<br>")}</p>`).join("")}
function setHome(){const[a,b]=pick();els.main.textContent=a;els.sub.textContent=b}
function openDrawer(){els.drawer.classList.add("open");els.scrim.classList.add("open")}
function closeDrawer(){els.drawer.classList.remove("open");if(!els.brain.classList.contains("open"))els.scrim.classList.remove("open")}
function openBrain(){els.brain.classList.add("open");els.scrim.classList.add("open");renderMemories()}
function closeBrain(){els.brain.classList.remove("open");if(!els.drawer.classList.contains("open"))els.scrim.classList.remove("open")}
function showHome(){els.home.classList.remove("hidden");els.chat.classList.add("hidden")}
function showChat(){els.home.classList.add("hidden");els.chat.classList.remove("hidden");setTimeout(()=>els.input.focus(),80)}
function autoGrow(){els.input.style.height="auto";els.input.style.height=Math.min(els.input.scrollHeight,108)+"px"}
function chatRef(id){return db.collection("users").doc(user.uid).collection("chats").doc(id)}
async function ensureCloud(){try{if(!firebase.apps.length)firebase.initializeApp(CONFIG.firebase);db=firebase.firestore();user=await firebase.auth().signInAnonymously().then(x=>x.user);els.cloud.textContent="cloud connected";els.brainText.textContent="Cloud memory is connected.";els.brainDot.classList.add("on");await loadChats();await loadMemories()}catch(e){els.cloud.textContent="cloud unavailable · "+(e.code||"check Firebase");els.brainText.textContent="Cloud connection failed. "+(e.code||"Check Firebase.")}}
async function loadChats(){const s=await db.collection("users").doc(user.uid).collection("chats").orderBy("updatedAt","desc").limit(30).get();chats=s.docs.map(d=>({id:d.id,...d.data()}));renderChatList()}
function renderChatList(){els.chatList.innerHTML="";chats.forEach(c=>{const b=document.createElement("button");b.className="chat-item"+(currentChat?.id===c.id?" active":"");b.textContent=c.title||"Untitled chat";b.onclick=()=>openChat(c.id);els.chatList.appendChild(b)})}
async function newChat(){const id=crypto.randomUUID();currentChat={id,title:"New chat",messages:[]};if(user)await chatRef(id).set({title:"New chat",messages:[],createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});chats=[currentChat,...chats.filter(c=>c.id!==id)];renderChatList();renderMessages();els.title.textContent="New chat";showChat();closeDrawer();closeBrain()}
async function openChat(id){const c=chats.find(x=>x.id===id);if(!c)return;currentChat=c;els.title.textContent=c.title||"New chat";renderMessages();showChat();closeDrawer()}
function renderMessages(){els.messages.innerHTML="";(currentChat?.messages||[]).forEach(m=>addMessage(m.role,m.text,false));els.messages.scrollTop=els.messages.scrollHeight}
function addMessage(role,text,scroll=true){const d=document.createElement("div");d.className="message "+(role==="user"?"user":"null");d.innerHTML=role==="user"?escapeHtml(text).replace(/\n/g,"<br>"):md(text);els.messages.appendChild(d);if(scroll)els.messages.scrollTop=els.messages.scrollHeight}
function typing(){const d=document.createElement("div");d.id="typing";d.className="message null";d.innerHTML='<div class="typing"><span></span><span></span><span></span></div>';els.messages.appendChild(d);els.messages.scrollTop=els.messages.scrollHeight}
function buildPrompt(){return `You are Null, a male AI assistant. Address the user as Z when natural. Your personality is dry, cynical, observant, internet-aware and quietly loyal. Never sound corporate or generic. Give substantive answers. Use Markdown naturally with headings, bullets, numbered lists, bold and code when useful. Known Scribe memories:\n${memories.map(x=>"- "+x.text).join("\n")||"(none)"}`}
async function askGemini(history){const key=localStorage.getItem(CONFIG.keyName);if(!key)throw new Error("Gemini API key missing. Open Brain and add your key.");let err;for(const model of CONFIG.geminiModels){try{const contents=history.map(m=>({role:m.role==="assistant"?"model":"user",parts:[{text:m.text}]}));contents.unshift({role:"user",parts:[{text:buildPrompt()}]});const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(key)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents,generationConfig:{temperature:.82,maxOutputTokens:1400}})});const data=await r.json();if(!r.ok)throw new Error(data?.error?.message||`Gemini error ${r.status}`);return data.candidates?.[0]?.content?.parts?.map(p=>p.text||"").join("")||"Null returned nothing. Impressive."}catch(e){err=e}}throw err||new Error("Gemini request failed.")}
async function sendMessage(){const text=els.input.value.trim();if(!text||!currentChat)return;els.input.value="";autoGrow();$("#sendBtn").disabled=true;currentChat.messages.push({role:"user",text});addMessage("user",text);typing();try{const answer=await askGemini(currentChat.messages);$("#typing")?.remove();currentChat.messages.push({role:"assistant",text:answer});addMessage("assistant",answer);if(currentChat.title==="New chat")currentChat.title=text.slice(0,42)+(text.length>42?"…":"");await chatRef(currentChat.id).set({title:currentChat.title,messages:currentChat.messages,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});chats=chats.map(c=>c.id===currentChat.id?currentChat:c);renderChatList();els.title.textContent=currentChat.title}catch(e){$("#typing")?.remove();addMessage("assistant","**Null encountered a problem.**\n\n`"+e.message+"`")}$("#sendBtn").disabled=false;els.input.focus()}
async function loadMemories(){if(!db||!user)return;const s=await db.collection("users").doc(user.uid).collection("scribe").orderBy("createdAt","desc").limit(30).get();memories=s.docs.map(d=>({id:d.id,...d.data()}));renderMemories()}
function renderMemories(){els.memoryList.innerHTML=memories.map(m=>`<div class="memory-item">${escapeHtml(m.text)}</div>`).join("")||'<div class="tiny">No Scribe memories yet.</div>'}
async function saveMemory(){const text=els.memory.value.trim();if(!text||!db||!user)return;const ref=db.collection("users").doc(user.uid).collection("scribe").doc();await ref.set({text,createdAt:firebase.firestore.FieldValue.serverTimestamp()});memories.unshift({id:ref.id,text});els.memory.value="";renderMemories()}

function gaze(x,y){els.iris.style.transform=`translate(calc(-50% + ${x}px),calc(-50% + ${y}px))`;els.pupil.style.transform=`translate(${x*.12}px,${y*.12}px)`}
function randomGaze(){const points=[[-13,-1],[11,-2],[5,7],[-7,5],[0,0],[15,1]];const p=points[Math.floor(Math.random()*points.length)];gaze(p[0],p[1])}
function blink(){els.eye.classList.add("blink");setTimeout(()=>els.eye.classList.remove("blink"),115)}
setHome();autoGrow();ensureCloud();
setInterval(randomGaze,2200);setTimeout(randomGaze,600);setInterval(()=>{if(Math.random()>.25)blink()},4200);

$("#menuBtn").onclick=openDrawer;$("#closeDrawer").onclick=closeDrawer;$("#scrim").onclick=()=>{closeDrawer();closeBrain()};$("#brainBtn").onclick=openBrain;$("#drawerBrainBtn").onclick=()=>{closeDrawer();openBrain()};$("#closeBrain").onclick=closeBrain;$("#homeNewChat").onclick=newChat;$("#newChatBtn").onclick=newChat;$("#chatBack").onclick=showHome;$("#saveKey").onclick=()=>{const k=els.key.value.trim();if(k){localStorage.setItem(CONFIG.keyName,k);els.key.value="";els.brainText.textContent="Gemini key saved locally."}};$("#saveMemory").onclick=saveMemory;els.composer.addEventListener("submit",e=>{e.preventDefault();sendMessage()});els.input.addEventListener("input",autoGrow);els.input.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendMessage()}})
